### ISSUE TITLE
The colour of the events doesn't fit with calendar colour

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#7]
Those events are from gmail calendar (red) and they are on (blue)

![image](https://user-images.githubusercontent.com/8724844/33063752-b117d790-cea3-11e7-8b55-e84c4504ddf0.png)

look it on native app:

![image](https://user-images.githubusercontent.com/8724844/33063790-cc037eb0-cea3-11e7-8d2b-27503609e5cb.png)

**Comment by umair-brainx** [comment]
Fixed. Now its showing for me

**Comment by umair-brainx** [comment]
Native:
![screen shot 2018-01-11 at 3 53 57 pm](https://user-images.githubusercontent.com/26704318/34822163-c6bdeea6-f6e7-11e7-8ef3-2f416ceed0dc.png)

Our app:
![screen shot 2018-01-11 at 3 54 11 pm](https://user-images.githubusercontent.com/26704318/34822194-df042228-f6e7-11e7-822c-e9db6aaa20b3.png)

**Comment by jorge9200** [comment]
Is not fixed for me yet, look:

Native calendar (2 calendars gmail "red" and super calendar "yellow") the events appear red and yellow
![image](https://user-images.githubusercontent.com/8724844/34830270-b36fc396-f6e3-11e7-97f1-b7c06ba6315e.png)

Horbito app (2 calendars gmail "red" and super calendar "yellow") the events appear BLUE
![image](https://user-images.githubusercontent.com/8724844/34830351-e614a190-f6e3-11e7-981f-912fa962ea76.png)

**Comment by umair-brainx** [comment]
@jorge9200 I am not sure whats wrong with you. but for me its working fine. Can you debug this with @icastillejogomez and update me if there is something wrong from my side.

**Comment by jorge9200** [comment]
@umair-brainx  But i think is not working for you neither, can you show me 2 different color (calendars) working on your app?

In the image you showed me the events are red and your calendars are blue and red. So check it on https://developers.google.com/google-apps/calendar/v3/reference/ and tell us if there is a problem with our api

**Comment by umair-brainx** [comment]
Previously I was assigning color to an event only if that specific event has color.
Now I am assigning the calendar color to all its events. Kindly have a look.

**Comment by jorge9200** [comment]
Seems fixed!
